FROM node:21-alpine

# Create app directory
WORKDIR /backend

# Install app dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm i -g nodemon

ENV NODE_ENV=development

CMD [ "nodemon", "index.js" ]
