version: "3"
services:
  mongo:
    container_name: mongo_avilatek
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: node_avilatek
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - default
    volumes:
      - .:/backend
      - nodemodules_backend:/backend/node_modules
      - ./signatureImages:/backend/signatureImages
      - ./logs.log:/backend/logs.log
      - ./exceptions.log:/backend/exceptions.log
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo:27017/ecommerce
      - API_URL=http://localhost:3003/api
    env_file:
      - ./.env.development
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "3003:3003"


networks:
  default:
    name: backend-database-network


volumes:
  nodemodules_backend: